server {
    listen 80;
    server_name anjen.net www.anjen.net;
    return 301 https://www.anjen.net$request_uri; 
}

server {
    listen 443 ssl;
    server_name www.anjen.net;

    ssl_certificate /etc/nginx/ssl/www.anjen.net_bundle.crt;
    ssl_certificate_key /etc/nginx/ssl/www.anjen.net.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 50M;
    root /www/travelmap/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        alias /www/travelmap/backend/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
